using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Migs.ValueTypes.DataTypes
{
    /// <summary>
    /// ISO-3166-1 alpha-2 and alpha-3
    /// </summary>
    public readonly record struct CountryData
    {
        #region properties

        public string Name { get; }
        public string Alpha2Code { get; }
        public string Alpha3Code { get; }
        public string NumericCode { get; }

        #endregion

        #region constructor
        
        public CountryData()
        {
            Name = "";
            Alpha2Code = "";
            Alpha3Code = "";
            NumericCode = "";
        }

        public CountryData(string name, string alpha2, string alpha3, string numeric)
        {
            Name = name ?? "";
            Alpha2Code = alpha2 ?? "";
            Alpha3Code = alpha3 ?? "";
            NumericCode = numeric ?? "";
        }

        #endregion
    }

    public static partial class Data
    {
        public static ReadOnlyCollection<CountryData> Countries = new(_countries);
        private static List<CountryData> _countries =>
        [
            new CountryData("Afghanistan", "AF", "AFG", "004"),
            new CountryData("Åland Islands", "AX", "ALA", "248"),
            new CountryData("Albania", "AL", "ALB", "008"),
            new CountryData("Algeria", "DZ", "DZA", "012"),
            new CountryData("American Samoa", "AS", "ASM", "016"),
            new CountryData("Andorra", "AD", "AND", "020"),
            new CountryData("Angola", "AO", "AGO", "024"),
            new CountryData("Anguilla", "AI", "AIA", "660"),
            new CountryData("Antarctica", "AQ", "ATA", "010"),
            new CountryData("Antigua and Barbuda", "AG", "ATG", "028"),
            new CountryData("Argentina", "AR", "ARG", "032"),
            new CountryData("Armenia", "AM", "ARM", "051"),
            new CountryData("Aruba", "AW", "ABW", "533"),
            new CountryData("Australia", "AU", "AUS", "036"),
            new CountryData("Austria", "AT", "AUT", "040"),
            new CountryData("Azerbaijan", "AZ", "AZE", "031"),
            new CountryData("Bahamas", "BS", "BHS", "044"),
            new CountryData("Bahrain", "BH", "BHR", "048"),
            new CountryData("Bangladesh", "BD", "BGD", "050"),
            new CountryData("Barbados", "BB", "BRB", "052"),
            new CountryData("Belarus", "BY", "BLR", "112"),
            new CountryData("Belgium", "BE", "BEL", "056"),
            new CountryData("Belize", "BZ", "BLZ", "084"),
            new CountryData("Benin", "BJ", "BEN", "204"),
            new CountryData("Bermuda", "BM", "BMU", "060"),
            new CountryData("Bhutan", "BT", "BTN", "064"),
            new CountryData("Bolivia, Plurinational State of", "BO", "BOL", "068"),
            new CountryData("Bonaire, Sint Eustatius and Saba[d]", "BQ", "BES", "535"),
            new CountryData("Bosnia and Herzegovina", "BA", "BIH", "070"),
            new CountryData("Botswana", "BW", "BWA", "072"),
            new CountryData("Bouvet Island", "BV", "BVT", "074"),
            new CountryData("Brazil", "BR", "BRA", "076"),
            new CountryData("British Indian Ocean Territory", "IO", "IOT", "086"),
            new CountryData("Brunei Darussalam", "BN", "BRN", "096"),
            new CountryData("Bulgaria", "BG", "BGR", "100"),
            new CountryData("Burkina Faso", "BF", "BFA", "854"),
            new CountryData("Burundi", "BI", "BDI", "108"),
            new CountryData("Cabo Verde", "CV", "CPV", "132"),
            new CountryData("Cambodia", "KH", "KHM", "116"),
            new CountryData("Cameroon", "CM", "CMR", "120"),
            new CountryData("Canada", "CA", "CAN", "124"),
            new CountryData("Cayman Islands", "KY", "CYM", "136"),
            new CountryData("Central African Republic", "CF", "CAF", "140"),
            new CountryData("Chad", "TD", "TCD", "148"),
            new CountryData("Chile", "CL", "CHL", "152"),
            new CountryData("China", "CN", "CHN", "156"),
            new CountryData("Christmas Island", "CX", "CXR", "162"),
            new CountryData("Cocos (Keeling) Islands", "CC", "CCK", "166"),
            new CountryData("Colombia", "CO", "COL", "170"),
            new CountryData("Comoros", "KM", "COM", "174"),
            new CountryData("Congo", "CG", "COG", "178"),
            new CountryData("Congo, Democratic Republic of the", "CD", "COD", "180"),
            new CountryData("Cook Islands", "CK", "COK", "184"),
            new CountryData("Costa Rica", "CR", "CRI", "188"),
            new CountryData("Côte d'Ivoire", "CI", "CIV", "384"),
            new CountryData("Croatia", "HR", "HRV", "191"),
            new CountryData("Cuba", "CU", "CUB", "192"),
            new CountryData("Curaçao", "CW", "CUW", "531"),
            new CountryData("Cyprus", "CY", "CYP", "196"),
            new CountryData("Czechia", "CZ", "CZE", "203"),
            new CountryData("Denmark", "DK", "DNK", "208"),
            new CountryData("Djibouti", "DJ", "DJI", "262"),
            new CountryData("Dominica", "DM", "DMA", "212"),
            new CountryData("Dominican Republic", "DO", "DOM", "214"),
            new CountryData("Ecuador", "EC", "ECU", "218"),
            new CountryData("Egypt", "EG", "EGY", "818"),
            new CountryData("El Salvador", "SV", "SLV", "222"),
            new CountryData("Equatorial Guinea", "GQ", "GNQ", "226"),
            new CountryData("Eritrea", "ER", "ERI", "232"),
            new CountryData("Estonia", "EE", "EST", "233"),
            new CountryData("Eswatini", "SZ", "SWZ", "748"),
            new CountryData("Ethiopia", "ET", "ETH", "231"),
            new CountryData("Falkland Islands (Malvinas)", "FK", "FLK", "238"),
            new CountryData("Faroe Islands", "FO", "FRO", "234"),
            new CountryData("Fiji", "FJ", "FJI", "242"),
            new CountryData("Finland", "FI", "FIN", "246"),
            new CountryData("France", "FR", "FRA", "250"),
            new CountryData("French Guiana", "GF", "GUF", "254"),
            new CountryData("French Polynesia", "PF", "PYF", "258"),
            new CountryData("French Southern Territories", "TF", "ATF", "260"),
            new CountryData("Gabon", "GA", "GAB", "266"),
            new CountryData("Gambia", "GM", "GMB", "270"),
            new CountryData("Georgia", "GE", "GEO", "268"),
            new CountryData("Germany", "DE", "DEU", "276"),
            new CountryData("Ghana", "GH", "GHA", "288"),
            new CountryData("Gibraltar", "GI", "GIB", "292"),
            new CountryData("Greece", "GR", "GRC", "300"),
            new CountryData("Greenland", "GL", "GRL", "304"),
            new CountryData("Grenada", "GD", "GRD", "308"),
            new CountryData("Guadeloupe", "GP", "GLP", "312"),
            new CountryData("Guam", "GU", "GUM", "316"),
            new CountryData("Guatemala", "GT", "GTM", "320"),
            new CountryData("Guernsey", "GG", "GGY", "831"),
            new CountryData("Guinea", "GN", "GIN", "324"),
            new CountryData("Guinea-Bissau", "GW", "GNB", "624"),
            new CountryData("Guyana", "GY", "GUY", "328"),
            new CountryData("Haiti", "HT", "HTI", "332"),
            new CountryData("Heard Island and McDonald Islands", "HM", "HMD", "334"),
            new CountryData("Holy See", "VA", "VAT", "336"),
            new CountryData("Honduras", "HN", "HND", "340"),
            new CountryData("Hong Kong", "HK", "HKG", "344"),
            new CountryData("Hungary", "HU", "HUN", "348"),
            new CountryData("Iceland", "IS", "ISL", "352"),
            new CountryData("India", "IN", "IND", "356"),
            new CountryData("Indonesia", "ID", "IDN", "360"),
            new CountryData("Iran, Islamic Republic of", "IR", "IRN", "364"),
            new CountryData("Iraq", "IQ", "IRQ", "368"),
            new CountryData("Ireland", "IE", "IRL", "372"),
            new CountryData("Isle of Man", "IM", "IMN", "833"),
            new CountryData("Israel", "IL", "ISR", "376"),
            new CountryData("Italy", "IT", "ITA", "380"),
            new CountryData("Jamaica", "JM", "JAM", "388"),
            new CountryData("Japan", "JP", "JPN", "392"),
            new CountryData("Jersey", "JE", "JEY", "832"),
            new CountryData("Jordan", "JO", "JOR", "400"),
            new CountryData("Kazakhstan", "KZ", "KAZ", "398"),
            new CountryData("Kenya", "KE", "KEN", "404"),
            new CountryData("Kiribati", "KI", "KIR", "296"),
            new CountryData("Korea, Democratic People's Republic of", "KP", "PRK", "408"),
            new CountryData("Korea, Republic of", "KR", "KOR", "410"),
            new CountryData("Kuwait", "KW", "KWT", "414"),
            new CountryData("Kyrgyzstan", "KG", "KGZ", "417"),
            new CountryData("Lao People's Democratic Republic", "LA", "LAO", "418"),
            new CountryData("Latvia", "LV", "LVA", "428"),
            new CountryData("Lebanon", "LB", "LBN", "422"),
            new CountryData("Lesotho", "LS", "LSO", "426"),
            new CountryData("Liberia", "LR", "LBR", "430"),
            new CountryData("Libya", "LY", "LBY", "434"),
            new CountryData("Liechtenstein", "LI", "LIE", "438"),
            new CountryData("Lithuania", "LT", "LTU", "440"),
            new CountryData("Luxembourg", "LU", "LUX", "442"),
            new CountryData("Macao", "MO", "MAC", "446"),
            new CountryData("Madagascar", "MG", "MDG", "450"),
            new CountryData("Malawi", "MW", "MWI", "454"),
            new CountryData("Malaysia", "MY", "MYS", "458"),
            new CountryData("Maldives", "MV", "MDV", "462"),
            new CountryData("Mali", "ML", "MLI", "466"),
            new CountryData("Malta", "MT", "MLT", "470"),
            new CountryData("Marshall Islands", "MH", "MHL", "584"),
            new CountryData("Martinique", "MQ", "MTQ", "474"),
            new CountryData("Mauritania", "MR", "MRT", "478"),
            new CountryData("Mauritius", "MU", "MUS", "480"),
            new CountryData("Mayotte", "YT", "MYT", "175"),
            new CountryData("Mexico", "MX", "MEX", "484"),
            new CountryData("Micronesia, Federated States of", "FM", "FSM", "583"),
            new CountryData("Moldova, Republic of", "MD", "MDA", "498"),
            new CountryData("Monaco", "MC", "MCO", "492"),
            new CountryData("Mongolia", "MN", "MNG", "496"),
            new CountryData("Montenegro", "ME", "MNE", "499"),
            new CountryData("Montserrat", "MS", "MSR", "500"),
            new CountryData("Morocco", "MA", "MAR", "504"),
            new CountryData("Mozambique", "MZ", "MOZ", "508"),
            new CountryData("Myanmar", "MM", "MMR", "104"),
            new CountryData("Namibia", "NA", "NAM", "516"),
            new CountryData("Nauru", "NR", "NRU", "520"),
            new CountryData("Nepal", "NP", "NPL", "524"),
            new CountryData("Netherlands, Kingdom of the", "NL", "NLD", "528"),
            new CountryData("New Caledonia", "NC", "NCL", "540"),
            new CountryData("New Zealand", "NZ", "NZL", "554"),
            new CountryData("Nicaragua", "NI", "NIC", "558"),
            new CountryData("Niger", "NE", "NER", "562"),
            new CountryData("Nigeria", "NG", "NGA", "566"),
            new CountryData("Niue", "NU", "NIU", "570"),
            new CountryData("Norfolk Island", "NF", "NFK", "574"),
            new CountryData("North Macedonia", "MK", "MKD", "807"),
            new CountryData("Northern Mariana Islands", "MP", "MNP", "580"),
            new CountryData("Norway", "NO", "NOR", "578"),
            new CountryData("Oman", "OM", "OMN", "512"),
            new CountryData("Pakistan", "PK", "PAK", "586"),
            new CountryData("Palau", "PW", "PLW", "585"),
            new CountryData("Palestine, State of", "PS", "PSE", "275"),
            new CountryData("Panama", "PA", "PAN", "591"),
            new CountryData("Papua New Guinea", "PG", "PNG", "598"),
            new CountryData("Paraguay", "PY", "PRY", "600"),
            new CountryData("Peru", "PE", "PER", "604"),
            new CountryData("Philippines", "PH", "PHL", "608"),
            new CountryData("Pitcairn", "PN", "PCN", "612"),
            new CountryData("Poland", "PL", "POL", "616"),
            new CountryData("Portugal", "PT", "PRT", "620"),
            new CountryData("Puerto Rico", "PR", "PRI", "630"),
            new CountryData("Qatar", "QA", "QAT", "634"),
            new CountryData("Réunion", "RE", "REU", "638"),
            new CountryData("Romania", "RO", "ROU", "642"),
            new CountryData("Russian Federation", "RU", "RUS", "643"),
            new CountryData("Rwanda", "RW", "RWA", "646"),
            new CountryData("Saint Barthélemy", "BL", "BLM", "652"),
            new CountryData("Saint Helena, Ascension and Tristan da Cunha[e]", "SH", "SHN", "654"),
            new CountryData("Saint Kitts and Nevis", "KN", "KNA", "659"),
            new CountryData("Saint Lucia", "LC", "LCA", "662"),
            new CountryData("Saint Martin (French part)", "MF", "MAF", "663"),
            new CountryData("Saint Pierre and Miquelon", "PM", "SPM", "666"),
            new CountryData("Saint Vincent and the Grenadines", "VC", "VCT", "670"),
            new CountryData("Samoa", "WS", "WSM", "882"),
            new CountryData("San Marino", "SM", "SMR", "674"),
            new CountryData("Sao Tome and Principe", "ST", "STP", "678"),
            new CountryData("Saudi Arabia", "SA", "SAU", "682"),
            new CountryData("Senegal", "SN", "SEN", "686"),
            new CountryData("Serbia", "RS", "SRB", "688"),
            new CountryData("Seychelles", "SC", "SYC", "690"),
            new CountryData("Sierra Leone", "SL", "SLE", "694"),
            new CountryData("Singapore", "SG", "SGP", "702"),
            new CountryData("Sint Maarten (Dutch part)", "SX", "SXM", "534"),
            new CountryData("Slovakia", "SK", "SVK", "703"),
            new CountryData("Slovenia", "SI", "SVN", "705"),
            new CountryData("Solomon Islands", "SB", "SLB", "090"),
            new CountryData("Somalia", "SO", "SOM", "706"),
            new CountryData("South Africa", "ZA", "ZAF", "710"),
            new CountryData("South Georgia and the South Sandwich Islands", "GS", "SGS", "239"),
            new CountryData("South Sudan", "SS", "SSD", "728"),
            new CountryData("Spain", "ES", "ESP", "724"),
            new CountryData("Sri Lanka", "LK", "LKA", "144"),
            new CountryData("Sudan", "SD", "SDN", "729"),
            new CountryData("Suriname", "SR", "SUR", "740"),
            new CountryData("Svalbard and Jan Mayen[f]", "SJ", "SJM", "744"),
            new CountryData("Sweden", "SE", "SWE", "752"),
            new CountryData("Switzerland", "CH", "CHE", "756"),
            new CountryData("Syrian Arab Republic", "SY", "SYR", "760"),
            new CountryData("Taiwan, Province of China", "TW", "TWN", "158"),
            new CountryData("Tajikistan", "TJ", "TJK", "762"),
            new CountryData("Tanzania, United Republic of", "TZ", "TZA", "834"),
            new CountryData("Thailand", "TH", "THA", "764"),
            new CountryData("Timor-Leste", "TL", "TLS", "626"),
            new CountryData("Togo", "TG", "TGO", "768"),
            new CountryData("Tokelau", "TK", "TKL", "772"),
            new CountryData("Tonga", "TO", "TON", "776"),
            new CountryData("Trinidad and Tobago", "TT", "TTO", "780"),
            new CountryData("Tunisia", "TN", "TUN", "788"),
            new CountryData("Türkiye", "TR", "TUR", "792"),
            new CountryData("Turkmenistan", "TM", "TKM", "795"),
            new CountryData("Turks and Caicos Islands", "TC", "TCA", "796"),
            new CountryData("Tuvalu", "TV", "TUV", "798"),
            new CountryData("Uganda", "UG", "UGA", "800"),
            new CountryData("Ukraine", "UA", "UKR", "804"),
            new CountryData("United Arab Emirates", "AE", "ARE", "784"),
            new CountryData("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", "826"),
            new CountryData("United States of America", "US", "USA", "840"),
            new CountryData("United States Minor Outlying Islands[g]", "UM", "UMI", "581"),
            new CountryData("Uruguay", "UY", "URY", "858"),
            new CountryData("Uzbekistan", "UZ", "UZB", "860"),
            new CountryData("Vanuatu", "VU", "VUT", "548"),
            new CountryData("Venezuela, Bolivarian Republic of", "VE", "VEN", "862"),
            new CountryData("Viet Nam", "VN", "VNM", "704"),
            new CountryData("Virgin Islands (British)", "VG", "VGB", "092"),
            new CountryData("Virgin Islands (U.S.)", "VI", "VIR", "850"),
            new CountryData("Wallis and Futuna", "WF", "WLF", "876"),
            new CountryData("Western Sahara", "EH", "ESH", "732"),
            new CountryData("Yemen", "YE", "YEM", "887"),
            new CountryData("Zambia", "ZM", "ZMB", "894"),
            new CountryData("Zimbabwe", "ZW", "ZWE", "716"),
        ];
    }
}
