<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Smart.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	<LangVersion>default</LangVersion>
	<TargetFrameworks>net10.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Types\Address\" />
    <Folder Include="Types\Units\" />
  </ItemGroup>
</Project>
